# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estrategias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorRelevante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('justificacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Barrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrategias.Estrategia')),
            ],
        ),
        migrations.CreateModel(
            name='FactorHabilitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrategias.Estrategia')),
            ],
        ),
        migrations.CreateModel(
            name='Problematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrategias.Estrategia')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoIntermedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrategias.Objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionPolitica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrategias.Estrategia')),
            ],
        ),
        migrations.AddField(
            model_name='factorhabilitante',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrategias.Objetivo'),
        ),
        migrations.AddField(
            model_name='barrera',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrategias.Objetivo'),
        ),
        migrations.AddField(
            model_name='actorrelevante',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrategias.Objetivo'),
        ),
    ]
