# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estrategias', '0002_auto_20170714_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estrategia',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
