# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrategias', '0003_auto_20170728_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problematica',
            name='estrategia',
        ),
        migrations.AddField(
            model_name='estrategia',
            name='problematica',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Problematica',
        ),
    ]
