# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrategias', '0004_auto_20170818_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrategia',
            name='causas',
            field=models.TextField(default=''),
        ),
    ]
