# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrategias', '0005_estrategia_causas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causa',
            name='estrategia',
        ),
        migrations.RemoveField(
            model_name='solucionpolitica',
            name='estrategia',
        ),
        migrations.AddField(
            model_name='estrategia',
            name='solucionpolitica',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Causa',
        ),
        migrations.DeleteModel(
            name='SolucionPolitica',
        ),
    ]
