# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrategias', '0007_auto_20170908_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='barreras',
            field=models.TextField(),
        ),
    ]
