# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrategias', '0008_auto_20170908_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivo',
            name='estrategia',
        ),
        migrations.AddField(
            model_name='estrategia',
            name='objetivos',
            field=models.ManyToManyField(to='estrategias.Objetivo'),
        ),
    ]
